[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = ["chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/contracts/src/v0.8/", "foundry-devops/=lib/foundry-devops/src"]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]